name: import_lint
description: The Import Lint package defines import lint rules and report on
  lints found in Dart code.
version: 1.0.0
homepage: https://kawa.dev
repository: https://github.com/kawa1214/import-lint

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^6.4.1
  analyzer_plugin: ">=0.11.0 <0.13.0"
  args: ^2.3.0
  cli_util: ^0.3.5
  collection: ^1.17.1
  glob: ^2.0.2
  path: ^1.8.0
  yaml: ^3.1.0

dev_dependencies:
  coverage: 1.3.2
  # linter: ^1.30.0 #any #^1.23.0
  lints: any #2.0.1
  test: ^1.22.0
  test_reflective_loader: ^0.2.2
